# Generated by Django 2.0.3 on 2018-05-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
    ]
